[available_datasources]
client_datasource = "S3"
client_datasource_uri = "insightfinder-test"

[branding]
title = "Just another title"
background_image_url = "https://insightfinder-test.s3.amazonaws.com/static/background.png"
logo_url = "https://insightfinder-test.s3.amazonaws.com/static/logo.png"

[LLM-Models]
sagemaker_endpoint = "hf-llm-falcon-7b-instruct-bf16-2023-08-08-18-20-24-425"
sagemaker_region = "us-east-1"

[Embedding_Models]
hugging_face_endpoint = "https://bhjj98lm82dvt2bd.eastus.azure.endpoints.huggingface.cloud"
hugging_face_endpoint_qa = "https://aet52zbntx9zffq4.us-east-1.aws.endpoints.huggingface.cloud"
hugging_face_api_token = "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"
